services:
  web:
    image: nginx:latest
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - webnet

  ftp:
    image: fauria/vsftpd:latest
    container_name: ftp_server
    environment:
      - FTP_USER=user
      - FTP_PASS=password
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./ftp/ftp_data:/home/vsftpd
    networks:
      - webnet

networks:
  webnet:
